# config/default.yaml
app:
  name: myapp
  port: 8000

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: mydb

redis:
  host: 127.0.0.1
  port: 6379


logging:
  level: INFO
  when: MIDNIGHT
  interval: 1
  backupCount: 15
  log_dir: "./log"
  filename: "{app_name}.log"
  format: "[%(asctime)s][%(filename)s:%(lineno)d][%(levelname)s][%(thread)d][%(traceid)s][%(execution_time).2fs][%(message)s]"
