services:
  cronjob:
    image: cronjob:v0.12.6
    container_name: cronjob
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - /home/machine/data_volume/cronjob/logs:/app/logs
      - /home/machine/data_volume/cronjob/config:/app/config
    environment:
      - ENV=product
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
