version: '3.8'
services:
  cronjob:
    build:
      context: ../../../app/projects/cronjob
      dockerfile: ../../../deploy/docker/dockerfile/Dockerfile-cronjob
    container_name: cronjob
    working_dir: /app
    command: ["./cronjob", "--env=product", "--config=config/config.yaml"]
    ports:
      - "8080:8080"
    volumes:
      - ../../../app/projects/cronjob/logs:/app/logs
      - ../../../app/projects/cronjob/config/config.yaml:/app/config/config.yaml
    environment:
      - ENV=product
    restart: unless-stopped
