server:
  host: 0.0.0.0
  port: 8084
  access_log: false
logging:
  enabled: true
  level: INFO
  format: json
  output: file # options: stdout|stderr|file (if 'file', file_config applies)
  include_caller: true
  file_config:
    dir: ./logs
    filename: artemis
  rotate_config:
    enabled: true
    rotate_interval: 1d # unit decides suffix pattern automatically (m->YYYYMMDDHHMM)
    max_age: 72h
    cleanup_enabled: true
telemetry:
  enabled: true
  service_name: artemis
  sampling: always
  otlp:
    protocol: http   # http | grpc
    endpoint: #http://localhost:4318/v1/traces
    headers: {}
    timeout_ms: 5000
    # insecure only used for grpc; ignored for http
http_client:
  timeout_seconds: 5
  verify_ssl: true
  headers: {}

dept_services:
  cronjob:
    host: "192.168.31.72"
    port: 8082
  phoenixA:
    host: null
    port: null
